package com.alfilsoft.model;
// default package
// Generated Jul 9, 2018 4:19:10 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblbillTotals generated by hbm2java
 */
@Entity
@Table(name = "TBLBILL_TOTALS")
public class BillTotals implements java.io.Serializable {

	private Long id;
	private Long secshop;
	private Double allBillsTotals;
	private Double monthBillTotal;
	private Double yearBillTotal;

	public BillTotals() {
	}

	public BillTotals(Long id) {
		this.id = id;
	}

	public BillTotals(Long id, Long secshop, Double allBillsTotals, Double monthBillTotal,
			Double yearBillTotal) {
		this.id = id;
		this.secshop = secshop;
		this.allBillsTotals = allBillsTotals;
		this.monthBillTotal = monthBillTotal;
		this.yearBillTotal = yearBillTotal;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bill_totals_id_seq")
        @SequenceGenerator(name="bill_totals_id_seq", sequenceName = "TBLBILL_TOTALS_ID_SEQ")
	@Column(name = "SECBILL_TOTALS", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "SECSHOP")
	public Long getSecshop() {
		return this.secshop;
	}

	public void setSecshop(Long secshop) {
		this.secshop = secshop;
	}

	@Column(name = "ALL_BILLS_TOTALS", precision = 53, scale = 0)
	public Double getAllBillsTotals() {
		return this.allBillsTotals;
	}

	public void setAllBillsTotals(Double allBillsTotals) {
		this.allBillsTotals = allBillsTotals;
	}

	@Column(name = "MONTH_BILL_TOTAL", precision = 53, scale = 0)
	public Double getMonthBillTotal() {
		return this.monthBillTotal;
	}

	public void setMonthBillTotal(Double monthBillTotal) {
		this.monthBillTotal = monthBillTotal;
	}

	@Column(name = "YEAR_BILL_TOTAL", precision = 53, scale = 0)
	public Double getYearBillTotal() {
		return this.yearBillTotal;
	}

	public void setYearBillTotal(Double yearBillTotal) {
		this.yearBillTotal = yearBillTotal;
	}

}
