package com.alfilsoft.model;
// default package
// Generated Jul 9, 2018 4:19:10 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbldayBillTotal generated by hbm2java
 */
@Entity
@Table(name = "TBLDAY_BILL_TOTAL")
public class DayBillTotal implements java.io.Serializable {

    private Long id;
    private Shop shop;
    private Date date;
    private Double dayTotal;

    public DayBillTotal() {
    }

    public DayBillTotal(Long id) {
        this.id = id;
    }

    public DayBillTotal(Long id, Shop shop, Date date, Double dayTotal) {
        this.id = id;
        this.shop = shop;
        this.date = date;
        this.dayTotal = dayTotal;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "day_bill_total_id_seq")
    @SequenceGenerator(name = "day_bill_total_id_seq", sequenceName = "TBLDAY_BILL_TOTAL_ID_SEQ")
    @Column(name = "SECDAY_BILL_TOTAL", unique = true, nullable = false)
    public Long getSecdayBillTotal() {
        return this.id;
    }

    public void setSecdayBillTotal(Long id) {
        this.id = id;
    }

    @Column(name = "SECSHOP")
    public Shop getShop() {
        return this.shop;
    }

    public void setShop(Shop shop) {
        this.shop = shop;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DATE", length = 23)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "DAY_TOTAL", precision = 53, scale = 0)
    public Double getDayTotal() {
        return this.dayTotal;
    }

    public void setDayTotal(Double dayTotal) {
        this.dayTotal = dayTotal;
    }

}
