package com.alfilsoft.model;
// default package
// Generated Jul 9, 2018 4:19:10 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CrcitemDetail generated by hbm2java
 */
@Entity
@Table(name = "CRCITEM_DETAIL")
public class ItemDetail implements java.io.Serializable {

    private Long id;
    private Bill bill;
    private Item item;
    private Integer quantity;

    public ItemDetail() {
    }

    public ItemDetail(Long id) {
        this.id = id;
    }

    public ItemDetail(Long id, Bill bill, Item item, Integer quantity) {
        this.id = id;
        this.bill = bill;
        this.item = item;
        this.quantity = quantity;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "item_detail_id_seq")
    @SequenceGenerator(name = "item_detail_id_seq", sequenceName = "CRCITEM_DETAIL_ID_SEQ")
    @Column(name = "SECITEM_DETAIL", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "SECBILL",referencedColumnName = "SECBILL", nullable = false)
    public Bill getBill() {
        return this.bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    @ManyToOne
    @JoinColumn(name = "SECITEM")
    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @Column(name = "QUANTITY")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

}
