package com.alfilsoft.model;
// default package
// Generated Jul 9, 2018 4:19:10 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CrcshopUser generated by hbm2java
 */
@Entity
@Table(name = "CRCSHOP_USER")
public class ShopUser implements java.io.Serializable {

    private Long id;
    private Shop shop;
    private User user;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "shop_user_id_seq")
    @SequenceGenerator(name = "shop_user_id_seq", sequenceName = "CRCSHOP_USER_ID_SEQ")
    @Column(name = "SECSHOP_USER", nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "SECSHOP", nullable = false)
    public Shop getShop() {
        return this.shop;
    }

    public void setShop(Shop shop) {
        this.shop = shop;
    }

    @ManyToOne
    @JoinColumn(name = "SECUSER", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User secuser) {
        this.user = secuser;
    }
}
