package com.alfilsoft.model;
// default package
// Generated Jul 9, 2018 4:19:10 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblshopPay generated by hbm2java
 */
@Entity
@Table(name = "TBLSHOP_PAY")
public class ShopPay implements java.io.Serializable {

    private Long id;
    private Shop shop;
    private Double amount;
    private Date payDate;
    private Double limitDate;

    public ShopPay() {
    }

    public ShopPay(Long id) {
        this.id = id;
    }

    public ShopPay(Long id, Shop shop, Double amount, Date payDate, Double limitDate) {
        this.id = id;
        this.shop = shop;
        this.amount = amount;
        this.payDate = payDate;
        this.limitDate = limitDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "shop_pay_id_seq")
    @SequenceGenerator(name = "shop_pay_id_seq", sequenceName = "TBLSHOP_PAY_ID_SEQ")
    @Column(name = "SECSHOP_PAY", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "SECSHOP")
    public Shop getShop() {
        return this.shop;
    }

    public void setShop(Shop shop) {
        this.shop = shop;
    }

    @Column(name = "AMOUNT", precision = 53, scale = 0)
    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PAY_DATE", length = 23)
    public Date getPayDate() {
        return this.payDate;
    }

    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    @Column(name = "LIMIT_DATE", precision = 53, scale = 0)
    public Double getLimitDate() {
        return this.limitDate;
    }

    public void setLimitDate(Double limitDate) {
        this.limitDate = limitDate;
    }

}
